Create LICENSE
huaweicse/auth pull request #1
Opened 2018-02-01 11:05 UTC by asifdxtreme

2018-02-01 13:55 UTC, wangkirin requested changes
Please add NOTICE file, thank you

2018-02-07 10:39 UTC, asifdxtreme commented
@wangkirin , thanks for the suggestion, added the NOTICE file

2018-02-07 10:53 UTC, WillemJiang approved these changes

2018-02-07 11:49 UTC, wangkirin commented
LGTM

2018-02-07 11:49 UTC, wangkirin approved these changes

2018-02-07 11:50 UTC, merged