Add test case
huaweicse/auth pull request #5
Opened 2018-02-11 06:41 UTC by humingcheng

2018-02-11 09:52 UTC, tianxiaoliang requested changes

2018-02-11 09:52 UTC, tianxiaoliang commented on auth_test.go
> +func Test_UseAKSKAuth_UseShaAKSKAuth(t *testing.T) {
delete _

2018-02-23 06:44 UTC, humingcheng commented on auth_test.go
> +func Test_UseAKSKAuth_UseShaAKSKAuth(t *testing.T) {
It's fixed.

2018-02-23 06:46 UTC, tianxiaoliang commented
ok

2018-02-24 01:05 UTC, merged